name: petfinder_api_client
description: a Dart API Client for the Petfinder API.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.7.0

dependencies:
  freezed_annotation: ^3.0.0
  http: ^1.3.0
  json_annotation: ^4.9.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^6.0.0
