name: pet_finder
description: Helping pets find homes
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  animals_repository:
    path: ./packages/animals_repository
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  petfinder_api_client:
    path: ./packages/petfinder_api_client

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
