name: animals_repository
description: Dart package to manage the animals domain layer.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.7.0

dependencies:
  freezed_annotation: ^3.0.0
  petfinder_api_client:
    path: ../petfinder_api_client

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.3
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^6.0.0
